name: Work 2
on:
  push:
    branches:
      - "feature_a"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print test
        uses: dawidd6/action-send-mail@v4
        with:
        # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          #
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Cambios subidos a rama feature_a 
          # Required recipients' addresses:
          from: "u know who I am :c"
          to: ${{secrets.MAIL_USERNAME}}
          body: Build job of ${{github.repository}} feature_a completed successfully!

